/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.registration;

import controller.RegistrationController;
import java.awt.Container;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Nadeeshan
 */
public class ViewDailyRegistration extends javax.swing.JDialog {

    DateFormat dateFormat;

    /**
     * Creates new form ViewDailyRegistration
     */
    public ViewDailyRegistration(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        setModal(true);
        setLocation(280, 90);
        dateFormat = DateFormat.getDateInstance(DateFormat.MEDIUM);
        calendarCombo.setDateFormat(dateFormat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        reloadButton = new javax.swing.JButton();
        closelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        calendarCombo = new org.freixas.jcalendar.JCalendarCombo();
        printButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        infoTableScrollPane = new javax.swing.JScrollPane();
        infoTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Vani", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Daily Registration");

        reloadButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        reloadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/view-refresh-3.png"))); // NOI18N
        reloadButton.setText("Reload");
        reloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadButtonActionPerformed(evt);
            }
        });

        closelButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        closelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/window-close-3.png"))); // NOI18N
        closelButton.setText("Close");
        closelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closelButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel1.setText("Date :");

        calendarCombo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        calendarCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarComboActionPerformed(evt);
            }
        });

        printButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        printButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/printer-5.png"))); // NOI18N
        printButton.setText("Print");
        printButton.setEnabled(false);
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        infoTable.setFont(new java.awt.Font("Plantagenet Cherokee", 0, 17)); // NOI18N
        infoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Day Book No", "Book Type", "Volume", "Folio", "Land Name", "Village", "Extent", "Lot No", "Notry", "Deed No", "Value", "Reg. Duty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        infoTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        infoTable.setColumnSelectionAllowed(true);
        infoTable.getTableHeader().setReorderingAllowed(false);
        infoTableScrollPane.setViewportView(infoTable);
        infoTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        infoTable.getColumnModel().getColumn(0).setMinWidth(1);
        infoTable.getColumnModel().getColumn(3).setPreferredWidth(30);
        infoTable.getColumnModel().getColumn(7).setPreferredWidth(30);
        infoTable.getAccessibleContext().setAccessibleParent(infoTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(infoTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 2246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(infoTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(reloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(closelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calendarCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(360, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {closelButton, reloadButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calendarCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reloadButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(closelButton)
                        .addComponent(printButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {closelButton, reloadButton});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadButtonActionPerformed
        dateFormat = DateFormat.getDateInstance(DateFormat.SHORT);
        String date = dateFormat.format(calendarCombo.getDate());
        System.out.println(date);
        String[] formatDate = date.split("/");
        date = formatDate[2] + "/" + formatDate[0] + "/" + formatDate[1];
        int rowCount = infoTable.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            ((DefaultTableModel) infoTable.getModel()).removeRow(0);
        }
        try {
            if (RegistrationController.isRegistrationAvailableFor(date)) {
                ArrayList<ArrayList<String>> list = RegistrationController.getRegistrationInfo(date);
                for (int i = 0; i < list.size(); i++) {
                    ArrayList<String> registrationInfo = list.get(i);
                    String booktype = registrationInfo.get(0).startsWith("L") ? "LDO" : "General";
                    String extent = "A - " + registrationInfo.get(5) + "/ R - " + registrationInfo.get(6) + "/ P - " + registrationInfo.get(7);
                    String notry = registrationInfo.get(9) + " - " + registrationInfo.get(10);
                    Object[] row = {registrationInfo.get(0), booktype, registrationInfo.get(1), registrationInfo.get(2),
                        registrationInfo.get(3), registrationInfo.get(4), extent, registrationInfo.get(8), notry, registrationInfo.get(11),
                        registrationInfo.get(12), registrationInfo.get(13)};
                    ((DefaultTableModel) infoTable.getModel()).addRow(row);
                }
            } else {
                JLabel messageLabel = new JLabel("No record found for - " + date);
            messageLabel.setFont(new Font("High Tower Text", Font.PLAIN, 18));
                JOptionPane.showMessageDialog(this, messageLabel);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ViewDailyRegistration.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ViewDailyRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
        printButton.setEnabled(infoTable.getRowCount() > 0);
    }//GEN-LAST:event_reloadButtonActionPerformed

    private void closelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closelButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        setModal(false);
        try {
            Map<String, Object> param = new HashMap<String, Object>();
            dateFormat = DateFormat.getDateInstance(DateFormat.MEDIUM);
            String date = dateFormat.format(calendarCombo.getDate());
            param.put("Date", date);
            DefaultTableModel tableModel = ((DefaultTableModel) infoTable.getModel());
            JRTableModelDataSource dataSource = new JRTableModelDataSource(tableModel);
            JasperReport jasperReport = JasperCompileManager.compileReport("./src/reports/DailyRegistrationReport.jrxml");
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, param, dataSource);
            
            JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
            Container contentPane = jasperViewer.getContentPane();
            JDialog jasperDialog = new JDialog(this, false);
            jasperDialog.setContentPane(contentPane);
            jasperDialog.setTitle("Print Preview");
            jasperDialog.setSize(Toolkit.getDefaultToolkit().getScreenSize());
            jasperDialog.setLocationRelativeTo(this);
            jasperDialog.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(ViewDailyRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_printButtonActionPerformed

    private void calendarComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarComboActionPerformed
        reloadButton.doClick();
    }//GEN-LAST:event_calendarComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDailyRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDailyRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDailyRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDailyRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ViewDailyRegistration dialog = new ViewDailyRegistration(new javax.swing.JFrame(), false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.freixas.jcalendar.JCalendarCombo calendarCombo;
    private javax.swing.JButton closelButton;
    private javax.swing.JTable infoTable;
    private javax.swing.JScrollPane infoTableScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printButton;
    private javax.swing.JButton reloadButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
